public class GitHubCodeGenerator {
    public static void main(String[] args) {
        // This is an example code snippet generated by Alibaba Cloud's Java API Explorer.
        System.out.println("Hello, this is a sample Java code.");
    }
}
